title: '[Feature Request]'

body:
    - type: markdown
      attributes:
          value: |
              **Thank you for taking the time to open a feature request! Please provide the following information to help us understand and implement your request.**
    - type: input
      id: title
      attributes:
          label: Title
          description: A clear, descriptive title that summarizes the feature request.
          placeholder: 'Enter the title of your feature request'
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Description
          description: Detailed explanation of the feature you are requesting. Include what problem it solves or what enhancement it brings.
          placeholder: 'Provide a detailed description of the feature request'
      validations:
          required: true

    - type: textarea
      id: use_case
      attributes:
          label: Use Case
          description: Describe a specific scenario or use case where this feature would be beneficial.
          placeholder: 'Describe a use case for the feature'
      validations:
          required: true

    - type: textarea
      id: current_behavior
      attributes:
          label: Current Behavior
          description: Explain how the system currently behaves without the requested feature.
          placeholder: 'Describe the current behavior'
      validations:
          required: true

    - type: textarea
      id: proposed_behavior
      attributes:
          label: Proposed Behavior
          description: Describe how the system should behave with the requested feature implemented.
          placeholder: 'Describe the proposed behavior'
      validations:
          required: true

    - type: textarea
      id: benefits
      attributes:
          label: Benefits
          description: Outline the benefits and advantages of implementing this feature.
          placeholder: 'List the benefits of the feature'
      validations:
          required: true

    - type: textarea
      id: potential_drawbacks
      attributes:
          label: Potential Drawbacks
          description: Identify any potential drawbacks or limitations of implementing this feature.
          placeholder: 'Mention any potential drawbacks'
      validations:
          required: false

    - type: textarea
      id: alternatives_considered
      attributes:
          label: Alternatives Considered
          description: List any alternative solutions or workarounds that have been considered.
          placeholder: 'List the alternatives considered'
      validations:
          required: false

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Any additional information or context that might be relevant to understanding the feature request.
          placeholder: 'Provide any additional context'
      validations:
          required: false

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: Indicate the priority of this feature request.
          options:
              - low
              - medium
              - high
              - critical
      validations:
          required: true

    - type: textarea
      id: related_issues
      attributes:
          label: Related Issues/Pull Requests
          description: If applicable, reference any related GitHub issues or pull requests.
          placeholder: 'Reference any related issues or pull requests'
      validations:
          required: false

    - type: input
      id: environment
      attributes:
          label: Environment
          description: Specify the environment or platform where the feature is requested to be implemented (e.g., web, desktop, mobile).
          placeholder: 'Specify the environment or platform'
      validations:
          required: true

    - type: textarea
      id: screenshots
      attributes:
          label: Screenshots or Mockups (optional)
          description: If applicable, include any visual aids such as screenshots or mockups to help illustrate the requested feature.
          placeholder: 'Include any screenshots or mockups'
      validations:
          required: false

    - type: textarea
      id: implementation_suggestions
      attributes:
          label: Implementation Suggestions (optional)
          description: Provide any suggestions or ideas for how the feature could be implemented.
          placeholder: 'Provide any implementation suggestions'
      validations:
          required: false

    - type: textarea
      id: collaboration
      attributes:
          label: Collaboration
          description: Express willingness to collaborate on the development of this feature, if applicable.
          placeholder: 'Express willingness to collaborate'
      validations:
          required: false
