name: Bug report
description: Create a bug report to help us improve
labels: [bug]

body:
    - type: markdown
      attributes:
          value: |
              Thank you for your time to report a bug to the Rio project.
    - type: markdown
      attributes:
          value: |
              Before submitting a new issue, **please do a quick search** to ensure it hasn't already been raised in the issue tracker. You can do this by going to [this link](https://github.com/rio-labs/rio/issues) and typing some words related to the issue in the search box next to the "New issue" button.
    - type: textarea
      attributes:
          label: Describe the bug
          description: 'A concise description of the issue you''re experiencing. **Example:** "NumberInput is parsing negative numbers incorrectly. When I use -100 as input, the value is correctly processed as -100, but the displayed value is -.100."'
      validations:
          required: true
    - type: textarea
      attributes:
          label: Steps to Reproduce
          description: |
              Steps to reproduce the behavior. **Example:** 
              1. Enter -100 into the NumberInput field.
              2. Observe the displayed value in the NumberInput field.
              3. Notice that the value is correctly processed as -100, but the displayed value is -.100.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Screenshots/Videos
          description: |
              If applicable, add screenshots or videos to help explain your problem.

              **Tip:** You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
    - type: dropdown
      attributes:
          label: Operating System
          description: Please select the operating system you're using. **Example:** "Windows". If you're using multiple Operating systems, please select all that apply.
          multiple: true
          options:
              - Windows
              - MacOS
              - Linux
              - Other
      validations:
          required: false
    - type: dropdown
      attributes:
          label: What browsers are you seeing the problem on?
          description: Please select the browser you're using. If you're using multiple browsers, please select all that apply.
          multiple: true
          options:
              - Chrome
              - Firefox
              - Safari
              - Edge
              - Opera
              - Internet Explorer
              - Other
      validations:
          required: false
    - type: input
      attributes:
          label: Browser version
          description: Please enter the version of the browser you're using. **Example:** "124.0.6367.60". You can find this by clicking on the three dots in the top right corner of your browser and selecting "Help" or "About". If you're using multiple browsers, please enter the version for each browser. **Example:** "124.0.6367.60 (Chrome), 88.1.1 (Firefox)"
      validations:
          required: false
    - type: dropdown
      attributes:
          label: What device are you using?
          description: Please select the device you're using.
          multiple: true
          options:
              - Desktop
              - Mobile
      validations:
          required: false
    - type: textarea
      attributes:
          label: Additional context
          description: |
              Add any other context about the problem here.

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
