blank_issues_enabled: true
contact_links:
    - name: Feature Request
      url: https://github.com/rio-labs/rio/discussions/categories/feature-requests
      about: Suggestions for new features or improvements to enhance the functionality and user experience!
    - name: Rio Questions and Discussions
      url: https://github.com/rio-labs/rio/discussions/categories/q-a
      about: Please ask and answer questions on the community forums.
    - name: Join the Community Discord
      url: https://discord.com/invite/7ejXaPwhyH
      about: Come and chat with other community members!
